### ISSUE TITLE
Very interesting !

### ISSUE THREAD

**Issue by grll** [czynot/COVID19_Prediction#1]
Very interesting looks like the data you used are still in an exponential phase!

I am glad you are using the package, let me know if you need any help / have questions about it.

And please don't forget to include the license before sharing :)

**Comment by czynot** [comment]
Ah thanks a lot. I would cherry-pick the License commit from your repository.

Also the situation here in India was that we saw absolutely no cumulative growth over 32 days, and the graph goes asymptomatic to the X-axis, which is a bad fit for the data. So I decided to drop that part, and now since we have really low number of data points to deal with, the graph seems to overfit. 

Best possible prediction would only come after at least 3 or 4 days I guess.
